sudo: required
language: cpp

services:
  - docker

before_install:
  - docker pull boxdot/flatdata-dev:15

env:
  - C_COMPILER=clang CXX_COMPILER=clang++
  - C_COMPILER=gcc CXX_COMPILER=g++

script:
  - |
    docker run -t \
      --user `id -u $USER` \
      -e C_COMPILER=${C_COMPILER} \
      -e CXX_COMPILER=${CXX_COMPILER} \
      -v $(pwd):/src \
      -v $(pwd)/build:/build \
      -w /build \
      boxdot/flatdata-dev /src/ci/build-and-test.sh

deploy:
  provider: pages
  local-dir: build/docs/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: sphinx_ci